### ISSUE TITLE
android deployment pipeline

### ISSUE THREAD

**Issue by ctumwebaze** [nkola/pothole-hunter-tracker#14]

**Comment by ctumwebaze** [comment]
## Acceptance Criteria
- [ ] Configuration to sign an apk
- [ ] Configuration to upload the apk to the playstore
- [ ] Jenkins build pipeline to run unit tests, instrumentation tests, and deploy to playstore
